version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mock"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m4a0n69qiss0"
s3_prefix = "mock"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
profile = "sahily-cli"
parameter_overrides = "EndpointSubcription=\"nerila4191@haikido.com\""
